[DEFAULT]
fetch-updates-in-background = yes

[app.aab4156021dca6008a2c665125fc22c7]
website = 
name = osu!
file_path = /home/and00pium/AppImages/osu.appimage

[app.cf15a1a9c715828a5e69effb6d088332]
name = 227pby8q59
file_path = /home/and00pium/AppImages/spotiflac.appimage

[app.bdaa232a5b5535463724a1a5ad87b13b]
name = c1r822a2ra
file_path = /home/and00pium/AppImages/kopuz.appimage

[app.cf15a1a9c715828a5e69effb6d088332.update_manager]
allow_prereleases = False
repo = spotbye/SpotiFLAC
repo_filename = SpotiFLAC.AppImage
manager = GithubUpdater

[app.bdaa232a5b5535463724a1a5ad87b13b.update_manager]
allow_prereleases = False
repo = Kopuz-org/kopuz
repo_filename = Kopuz_0.14.0_x86_64.AppImage
manager = GithubUpdater

[app.a88c825035bd47a7695df9f53450867a]
name = Kanban Pro
file_path = /home/and00pium/AppImages/kanban_pro.appimage

[app.41922de3419859e2a3b17e352052a4c9]
name = Murglar
file_path = /home/and00pium/AppImages/murglar.appimage

